ApprovalWFDemo/Controllers/ApprovalTaskController.cs
using System;
using System.Activities;
using System.Activities.DurableInstancing;
using System.Activities.XamlIntegration;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Runtime.DurableInstancing;
using System.Web.Mvc;
using System.Xaml;
using ApprovalWFDemo.Models;
using ApprovalWFDemo.ViewModels;
using ApprovalWFDemo.WorkFlow;
using Microsoft.AspNet.Identity;
using Microsoft.Activities.Extensions.Tracking;
using Newtonsoft.Json.Linq;

namespace ApprovalWFDemo.Controllers
{
    [Authorize]
    public class ApprovalTaskController : Controller
    {
        // GET: ApprovalItem
        
        public ActionResult MyApprovalItems()
        {
            var user = User.Identity.GetUserName();
            var result = new List<ApprovalItemViewModel>();
            using (var db = new BusinessDbContext())
            {
              var items = db.ApprovalItems.Where(x => x.Drafter == user).ToList();
                foreach (var approvalItem in items)
                {
                    var workFlowItme = db.WorkFlowItems.FirstOrDefault(x => x.WfBusinessId == approvalItem.Id);
                    result.Add(new ApprovalItemViewModel
                    {
                        Id = approvalItem.Id,
                        Title = approvalItem.Title,
                        Type = workFlowItme.WfType,
                        Status = workFlowItme.Wfstatus,
                        Applier = approvalItem.Applicant,
                        ApplyDate = approvalItem.CreateDate,
                        CompleteDate = approvalItem.CompleteDate,
                        Drafter = approvalItem.Drafter,
                    });
                }
            }
            return View(result);
        }

        public ActionResult ViewApprovalItem(int approvalId)
        {
            var model = new ApprovalItem();
            using (var db = new BusinessDbContext())
            {
                model = db.ApprovalItems.FirstOrDefault(x => x.Id == approvalId);
                if (model != null)
                {
                    var wf = db.WorkFlowItems.FirstOrDefault(i => i.WfBusinessId == model.Id);
                    ViewBag.WfWriteField = wf.WfWriteField;
                    ViewBag.WfFlowChart = wf.WfFlowChart;
                    ViewBag.instanceId = wf.WfInstanceId;
                }
            }
          
            return View(model);
        }

        public ActionResult MyWorkFlow()
        {
            var result = new List<WorkFlowViewModel>();
            var userName = User.Identity.GetUserName();
            using (var db = new BusinessDbContext())
            {
                var workFlowItems = db.WorkFlowItems.Where(x => x.WfCurrentUser == userName).ToList();
                var businessId = workFlowItems.Select(x => x.WfBusinessId).Distinct().ToList();
                var approvalItems = db.ApprovalItems.Where(x => businessId.Contains(x.Id)).ToList();
                foreach (var workFlowItem in workFlowItems)
                {
                    var curApprovalItem = approvalItems.FirstOrDefault(x => x.Id == workFlowItem.WfBusinessId);
                    result.Add(new WorkFlowViewModel {
                        Id = workFlowItem.WfBusinessId,
                        Title = curApprovalItem.Title,
                        WorkFlowType = workFlowItem.WfType,
                        ApplicantDate = curApprovalItem.CreateDate,
                        Applicant = curApprovalItem.Applicant,
                        ApplicantPhone = curApprovalItem.ApplicantPhone,
                        WfStatus = workFlowItem.Wfstatus,
                        WfDrafter = workFlowItem.WfDrafter,
                        WfBusinessUrl = workFlowItem.WfBussinessUrl
                    });
                }
            }
            return View(result);
        }

        public ActionResult CreateApprovalItem()
        {
            return View();
        }

        //起草审批任务，并持久化
        [Authorize]
        public JObject CreateWorkFlow()
        {
            var syncEvent = new AutoResetEvent(false);

            string currentUserId = User.Identity.GetUserId();
            var user = new ApplicationDbContext().Users.FirstOrDefault(x => x.Id == currentUserId);
            var wfinData = new WorkFlowInParameter
            {
                Drafter = user.UserName
            };
            var inputs = new Dictionary<string, object>();
            inputs.Add("WfIn", wfinData);

            var activity = CreateActivityFrom(Server.MapPath("~") + "\\WorkFlow\\ApprovalWorkFlow.xaml");
            var wfApp = new WorkflowApplication(new ApprovalWorkFlow(), inputs)
            {
                //创建持久化的存储位置
                InstanceStore = CreateInstanceStore(),
                PersistableIdle = delegate(WorkflowApplicationIdleEventArgs e)
                {
                    return PersistableIdleAction.Unload;
                },
                Completed = delegate(WorkflowApplicationCompletedEventArgs e)
                {

                },
                Aborted = delegate(WorkflowApplicationAbortedEventArgs e)
                {
                },
                Unloaded = delegate(WorkflowApplicationEventArgs e)
                {
                    syncEvent.Set();
                },
                OnUnhandledException = delegate(WorkflowApplicationUnhandledExceptionEventArgs e)
                {
                    return UnhandledExceptionAction.Terminate;
                },
                Idle = delegate(WorkflowApplicationIdleEventArgs e)
                {
                }
            };
            //追踪当前 workflow的运行状态
            var stateTracker = new StateMachineStateTracker(wfApp.WorkflowDefinition);
            wfApp.Extensions.Add(stateTracker);
            wfApp.Extensions.Add(new StateTrackerPersistenceProvider(stateTracker));
            var customTracker = new CustomTrackingParticipant(); // 获取activity 内部的变量
            wfApp.Extensions.Add(customTracker);
            Guid instanceId = wfApp.Id;
            wfApp.Run();
            syncEvent.WaitOne();
            var pt = stateTracker.PossibleTransitions;

            string[] strs = pt.Split(',');
            JObject json = new JObject(
                new JProperty("instanceId", instanceId),
                new JProperty("rows",
                    new JArray(
                        from r in strs
                        select new JObject(
                            new JProperty("ID", r.ToString()),
                            new JProperty("Name", r.ToString())))));
            return json;
        }

        public ActionResult DrafterToNextState(ApprovalItem approvalItem, Guid instanceId, string nextLink) //起草者到下一环节
        {
            AutoResetEvent syncEvent = new AutoResetEvent(false);

            WorkflowApplication wfApp = new WorkflowApplication(new ApprovalWorkFlow())
            {

                InstanceStore = CreateInstanceStore(),
                PersistableIdle = delegate(WorkflowApplicationIdleEventArgs e)
                {
                    return PersistableIdleAction.Unload;
                },
                Completed = delegate(WorkflowApplicationCompletedEventArgs e)
                {
                },
                Aborted = delegate(WorkflowApplicationAbortedEventArgs e)
                {
                },
                Unloaded = delegate(WorkflowApplicationEventArgs e)
                {
                    syncEvent.Set();
                },
                OnUnhandledException = delegate(WorkflowApplicationUnhandledExceptionEventArgs e)
                {
                    return UnhandledExceptionAction.Terminate;
                },
                Idle = delegate(WorkflowApplicationIdleEventArgs e)
                {
                }

            };
            var stateTracker = new StateMachineStateTracker(wfApp.WorkflowDefinition); //当前状态追踪
            wfApp.Extensions.Add(stateTracker);
            wfApp.Extensions.Add(new StateTrackerPersistenceProvider(stateTracker));
            var cu = new CustomTrackingParticipant(); //获取Activity内部变量
            wfApp.Extensions.Add(cu); //获取Activity内部变量需要的追踪器
            //Guid instanceId = wfApp.Id;
            var trackerInstance = StateMachineStateTracker.LoadInstance(instanceId, wfApp.WorkflowDefinition,
                ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString);
            wfApp.Load(instanceId);
            BookmarkResumptionResult result = wfApp.ResumeBookmark(trackerInstance.CurrentState, nextLink.Trim());
            syncEvent.WaitOne();
            string CurrentUser = cu.Outputs["CurrentUser"].ToString();
            string OpinionField = cu.Outputs["OpinionField"].ToString();
            string Drafter = cu.Outputs["Drafter"].ToString();
            var CurrentState = stateTracker.CurrentState;
            //var Pt = StateTracker.PossibleTransitions;
            ApplicationUser user =
                    new ApplicationDbContext().Users.Include(i => i.Roles).FirstOrDefault(i => i.UserName == Drafter);
                //获取当前用户username
            approvalItem.Drafter = Drafter;
            approvalItem.CreateDate = DateTime.Now;
            using (var db = new BusinessDbContext())
            {
                db.ApprovalItems.Add(approvalItem);
                try
                {
                    db.SaveChanges();
                }
                catch 
                {
                    var json = new
                    {
                        errorMsg = "添加业务数据出错"
                    };
                    return Json(json, "text/html", JsonRequestBehavior.AllowGet);
                }
           
            WorkFlowItem wf = new WorkFlowItem
            {
                WfInstanceId = instanceId,
                WfType = "IT服务申请",

ApprovalWFDemo/Views/ApprovalTask/CreateApprovalItem.cshtml
@model ApprovalWFDemo.Models.ApprovalItem


@{
    ViewBag.Title = "起草申请";
}
<p class="text-success"></p>


    <form method="post" id="approvalItemForm" class="form-horizontal">
    <div class="row">
        <div class="col-sm-12">
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label class="col-sm-3 control-label">标题：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control col-sm-9" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">申请人：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Applicant, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">联系电话：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.ApplicantPhone, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">描述：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">审批意见：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.DealwithpeopleOpinion, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">审批人：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.DealwithpeopleName, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">管理人意见：</label>
                <div class="col-sm-9">
                    @Html.DisplayFor(m => m.ManagerOpinion)
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <a href="#" class="btn btn-info col-sm-2" id="btnSave">
                <i class="glyphicon glyphicon-ok"></i> 提交
            </a>
        </div>
    </div>
</form>

@section scripts{
    <script type="text/javascript">
        var instanceId;
        $(document)
            .ready(function() {

                $("#btnSave")
                    .on('click',
                        function() {
                            debugger
                            var inputOptions = [];
                            $.getJSON("/ApprovalTask/CreateWorkFlow?time=" + new Date(),
                                function(data) {
                                    instanceId = data.instanceId;
                                    CurrentState = data.CurrentState;
                                    $.each(data.rows,
                                        function(i, item) {
                                            inputOptions.push({ text: item.Name, value: item.Name });
                                        });
                                    bootbox.prompt({
                                        title: "选择提交环节",
                                        inputType: 'select',
                                        inputOptions: inputOptions,
                                        callback: function(result) {
                                            console.log(result);
                                            saveWorkFlow(result);
                                            //save the approvalitem
                                        }
                                    });

                                });
                        });

                function saveWorkFlow(selectResult) {
                    if (selectResult !== "") {
                        $("#approvalItemForm")
                            .submit(function (e) {
                                var postData = $(e.target).serialize();
                                $.ajax({
                                    url: '/ApprovalTask/DrafterToNextState?instanceId=' +
                                        instanceId +
                                        "&nextLink=" +
                                        selectResult,
                                    type: 'post',
                                    data: postData,
                                    success: function(data, textStatus, jqXHR) {
                                        window.location.href = "/ApprovalTask/MyApprovalItems";
                                    }
                                });
                                e.preventDefault();
                            });
                        $("#approvalItemForm").submit();
                    }
                }
            });

    </script>
}

ApprovalWFDemo/Views/ApprovalTask/MyApprovalItems.cshtml
@using ApprovalWFDemo.ViewModels
@model List<ApprovalWFDemo.ViewModels.ApprovalItemViewModel>


@{
    ViewBag.Title = "我提交的审批任务";
}
<p class="text-success"></p>
<h3>@ViewBag.Title</h3>
<div class="row">
    <div class="col-sm-12">
        @if (Model.Count > 0)
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>标题</th>
                        <th>类型</th>
                        <th>当前状态</th>
                        <th>申请日期</th>
                        <th>审批完成日期</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id
                            </td>
                            <td>
                                <a href="@Url.Action("ViewApprovalItem","ApprovalTask",new {approvalId=@item.Id})" target="_blank">@item.Title</a>
                                
                            </td>
                            <td>@item.Type</td>
                            <td>@item.Status</td>
                            <td>@item.ApplyDate</td>
                            <td>@item.CompleteDate</td>
                        </tr>
                    }
                </tbody>

            </table>
        }
    </div>
</div>

ApprovalWFDemo/Views/ApprovalTask/MyWorkFlow.cshtml
@using ApprovalWFDemo.ViewModels
@model List<WorkFlowViewModel>


@{
    ViewBag.Title = "我的审批任务";
}
<p class="text-success"></p>
<h3>@ViewBag.Title</h3>
<div class="row">
    <div class="col-sm-2">
        <a href="@Url.Action("CreateApprovalItem")" class="btn btn-info">
            <i class="glyphicon glyphicon-plus">起草审批任务</i>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        @if (Model.Count > 0)
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>标题</th>
                        <th>类型</th>
                        <th>当前状态</th>
                        <th>申请人</th>
                        <th>申请人联系电话</th>
                        <th>申请日期</th>
                        <th>审批流程发起人</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var workFlowItem in Model)
                    {
                        <tr>
                            <td>@workFlowItem.Id
                            </td>
                            <td>
                                <a href="@workFlowItem.WfBusinessUrl" target="_blank">@workFlowItem.Title</a>
                                
                            </td>
                            <td>@workFlowItem.WorkFlowType</td>
                            <td>@workFlowItem.WfStatus</td>
                            <td>@workFlowItem.Applicant</td>
                            <td>@workFlowItem.ApplicantPhone</td>
                            <td>@workFlowItem.ApplicantDate</td>
                            <td>@workFlowItem.WfDrafter</td>
                        </tr>
                    }
                </tbody>

            </table>
        }
    </div>
</div>

ApprovalWFDemo/Views/ApprovalTask/OpenWorkFlow.cshtml
@model ApprovalWFDemo.Models.ApprovalItem


@{
    ViewBag.Title = "申请单审批";
}
<p class="text-success"></p>

<h3>@ViewBag.Title</h3>
    <form method="post" id="processApprovalItem" class="form-horizontal">
    <div class="row">
        <div class="col-sm-12">
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label class="col-sm-3 control-label">标题：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control col-sm-9" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">申请人：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Applicant, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">联系电话：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.ApplicantPhone, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">描述：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">审批意见：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.DealwithpeopleOpinion, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">审批人：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.DealwithpeopleName, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">管理人意见：</label>
                <div class="col-sm-9">
                    @Html.DisplayFor(m => m.ManagerOpinion)
                </div>
            </div>
            @if (@ViewBag.WfWriteField != "")
            {
                <div class="form-group">
                    <label class="col-sm-3 control-label">审批意见：</label>
                    <div class="col-sm-9">
                        <textarea class="form-control" id="iOpinion" name="Opinion" rows="5"></textarea>
                    </div>
                </div>
            }

        </div>
        <div class="col-sm-12">
            <a href="#" class="btn btn-info col-sm-2" id="btnSave">
                <i class="glyphicon glyphicon-ok"></i> 提交
            </a>
        </div>
    </div>
</form>

@section scripts{
    <script type="text/javascript">
        var instanceId;
        $(document)
            .ready(function() {

                $("#btnSave")
                    .on('click',
                        function() {
                            debugger
                            var inputOptions = [];
                            $.getJSON("/ApprovalTask/GetPossiblePath?id=@ViewBag.instanceId &time="+new Date(),
                                function(data) {
                                    $.each(data.rows,
                                        function(i, item) {
                                            inputOptions.push({ text: item.Name, value: item.Name });
                                        });
                                    bootbox.prompt({
                                        title: "选择提交环节",
                                        inputType: 'select',
                                        inputOptions: inputOptions,
                                        callback: function(result) {
                                            console.log(result);
                                            saveWorkFlow(result);
                                            //save the approvalitem
                                        }
                                    });

                                });
                        });

                function saveWorkFlow(selectResult) {
                    if (selectResult !== "") {
                        $("#processApprovalItem")
                            .submit(function (e) {
                                var postData = $(e.target).serialize();
                                $.ajax({
                                    url: '/ApprovalTask/ToNextState?instanceId= @ViewBag.instanceId &nextLink=' +
                                        selectResult,
                                    type: 'post',
                                    data: postData,
                                    success: function(data, textStatus, jqXHR) {
                                        window.location.href = "/ApprovalTask/MyApprovalItems";
                                    }
                                });
                                e.preventDefault();
                            });
                        $("#processApprovalItem").submit();
                    }
                }
            });

    </script>
}

ApprovalWFDemo/Views/ApprovalTask/ViewApprovalItem.cshtml
@model ApprovalWFDemo.Models.ApprovalItem


@{
    ViewBag.Title = "查看我的申请";
}
<p class="text-success"></p>
    <form method="post" class="form-horizontal">
    <div class="row">
        <div class="col-sm-12">
            @Html.HiddenFor(m => m.Id)
            <div class="form-group">
                <label class="col-sm-3 control-label">标题：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control col-sm-9" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">申请人：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.Applicant, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">联系电话：</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(m => m.ApplicantPhone, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">描述：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">审批意见：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.DealwithpeopleOpinion, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">审批人：</label>
                <div class="col-sm-9">
                    @Html.TextAreaFor(m => m.DealwithpeopleName, new { @class = "form-control", rows = "5" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">管理人意见：</label>
                <div class="col-sm-9">
                    @Html.DisplayFor(m => m.ManagerOpinion)
                </div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label">流程流转信息：</label>
                <div class="col-sm-9">
                    <p>@ViewBag.WfFlowChart</p>
                </div>
            </div>
        </div>
    </div>
</form>